### ISSUE TITLE
New working fork

### ISSUE THREAD

**Issue by juampiq6** [prongbang/screen_protector#13]
Hi guys, for those of you who were struggling to make this lib work on Android, i just forked it and added some fixes from other fork that consisted only on rolling back the latest Android changes that made the white screen appear...
I have not battled tested this, but for Android just a basic disable screenshot functionality can be reached.
The lib maintainer was making some other great things, but im guessing apparently he didnt have more time.

you can find it [here](https://github.com/juampiq6/screen_protector)

**Comment by prongbang** [comment]
Thank you very much.
