### ISSUE TITLE
Color' isn't a type

### ISSUE THREAD

**Issue by himani2022** [prongbang/screen_protector#15]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/screen_protector-1.1.4/lib/screen_protector.dart:76:51: Error: Type 'Color' not found.
  static Future<void> protectDataLeakageWithColor(Color color) async

**Comment by kader93t** [comment]
he should import 'package:flutter/material.dart';

**Comment by himani2022** [comment]
> he should import 'package:flutter/material.dart';

this worked, thanx alot

**Comment by prongbang** [comment]
Fixed version 1.1.5

Thank you for report 👍
