### ISSUE TITLE
await ScreenProtector.preventScreenshotOn() is not work on ios 12.5.6

### ISSUE THREAD

**Issue by ling9400** [prongbang/screen_protector#16]
await ScreenProtector.preventScreenshotOn() is not work on ios 12.5.6, it only works above ios 16.1

**Comment by ling9400** [comment]
preventScreenshotOn() is only worked above ios 13+

**Comment by chenjiangmin** [comment]
May I ask if there is a solution?
Is there an API that can implement this feature on iOS 12+

> preventScreenshotOn() is only worked above ios 13+
