### ISSUE TITLE
iOS 17 screenshot disable not working

### ISSUE THREAD

**Issue by jan-koz** [prongbang/screen_protector#22]
await ScreenProtector.preventScreenshotOn(); is not working on iOS 17 beta. I suppose it won't be working on iOS 17 which will be release Monday 18th September

**Comment by awnigharbia** [comment]
same here any solution ?

**Comment by zhaoyanxiang** [comment]
same here

**Comment by Mariluk** [comment]
Some changes here. I need it to work on iOS 17, but unfortunately it doesn't work :(

**Comment by awnigharbia** [comment]
I found a workaround. dm me for info.

**Comment by jan-koz** [comment]
> I found a workaround. dm me for info.

Why can't you post this workaround here so that everyone interested may have a look?

**Comment by vishalpatel1327** [comment]
@awnigharbia   can u please share the sol over here so all Dev can have access of it.

**Comment by jan-koz** [comment]
There is workaround available, you have to add following code to your AppDelegate.swift file.

At the bottom of the file:
`extension UIWindow {
func makeSecure() {
    let field = UITextField()
    field.isSecureTextEntry = true
    self.addSubview(field)
    field.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
    field.centerXAnchor.constraint(equalTo: self.centerXAnchor).isActive = true
    self.layer.superlayer?.addSublayer(field.layer)
    field.layer.sublayers?.last?.addSublayer(self.layer)
  }
}`

And then invoke makeSecure() in _application_ function:
`self.window.makeSecure()`

**Comment by Mariluk** [comment]
Is there any way to disable screen protection? I would need it on one screen in the app.

**Comment by prongbang** [comment]
Thank you for reporting the issue. We will address it as quickly as possible.

**Comment by prongbang** [comment]
Could you try using this version `screen_protector: ^1.3.2` to see if it might fix the issue you are currently facing?

**Comment by Mariluk** [comment]
> Could you try using this version `screen_protector: ^1.3.2` to see if it might fix the issue you are currently facing?

Everything works fine. Ty

**Comment by temirfe** [comment]
version 1.4.2 on iOS 17.5 not working
