### ISSUE TITLE
State.initState() must be a void method without an `async` keyword

### ISSUE THREAD

**Issue by temirfe** [prongbang/screen_protector#37]
added below code in stateful widget as shown in Readme 
`@override
  void initState() async {
    await ScreenProtector.protectDataLeakageOn();
    super.initState();
  }`

But having an error: State.initState() must be a void method without an `async` keyword.
Rather than awaiting on asynchronous work directly inside of initState, call a separate method to do
this work without awaiting it.

**Comment by prongbang** [comment]
Please try,

```dart
@override 
void initState() { 
  _protectDataLeakageOn();
  super.initState(); 
}

void _protectDataLeakageOff() async =>
      await ScreenProtector.protectDataLeakageOff();

void _protectDataLeakageOn() async =>
      await ScreenProtector.protectDataLeakageOn();
```
