### ISSUE TITLE
When Running my app in android facing below exception.

### ISSUE THREAD

**Issue by adnankhan74444** [prongbang/screen_protector#4]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.prongbang:screen-protector:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://jcenter.bintray.com/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://developer.huawei.com/repo/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - file:/Users/ramireddyinduri/.m2/repository/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://maven.aliyun.com/repository/jcenter/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
       - https://maven.aliyun.com/repository/google/com/github/prongbang/screen-protector/1.0.0/screen-protector-1.0.0.pom
     Required by:
         project :app > project :screen_protector

**Comment by adnankhan74444** [comment]
@prongbang

**Comment by hasnaintt** [comment]
Same issue.

**Comment by adnankhan74444** [comment]
@hasnaintt add below code in android/build.gradle you will resolve that issue.

 allprojects {
    repositories {
        maven { url 'https://jitpack.io/' }
    }
}
