### ISSUE TITLE
can you please add below methods for android as well.

### ISSUE THREAD

**Issue by adnankhan74444** [prongbang/screen_protector#5]
await ScreenProtector.protectDataLeakageWithColor(Colors.white);
await ScreenProtector.protectDataLeakageWithBlur();
await ScreenProtector.protectDataLeakageWithImage('LaunchImage');

**Comment by adnankhan74444** [comment]
@prongbang

**Comment by adnankhan74444** [comment]
@prongbang @benoitskipr still waiting for you response..

**Comment by adnankhan74444** [comment]
@prongbang @benoitskipr still waiting for you response..

**Comment by prongbang** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/6635954/209311307-69bed6cd-b1b1-4a64-b5e1-1f7bfbdb59c2.png">

Choose to use whichever one,

**Comment by adnankhan74444** [comment]
@prongbang 

Is below method will work for android we well ?

await ScreenProtector.protectDataLeakageWithImage('LaunchImage');
