### ISSUE TITLE
Could not find com.github.prongbang:screen-protector:1.0.0.

### ISSUE THREAD

**Issue by rehanyousaf447** [prongbang/screen_protector#8]
This plugin (1.1.1)  is not working on flutter 3.0 as dependencies was not able to found from "com.github.prongbang:screen-protector:1.0.0"
After adding this code in project level build.gradle , then it started working fine:

      maven {
            url "https://jitpack.io"
        }

**Comment by MohamedJalal28** [comment]
> This plugin (1.1.1) is not working on flutter 3.0 as dependencies was not able to found from "com.github.prongbang:screen-protector:1.0.0" After adding this code in project level build.gradle , then it started working fine:
> 
> ```
>   maven {
>         url "https://jitpack.io"
>     }
> ```

I add this one but after got stuck with white screen from where i put ScreenProtector.preventScreenshotOn();

**Comment by sejun2** [comment]
> 

Same here. 
on android, just a white screen appears...

**Comment by cnkygmr** [comment]
Same here.
on android, just a white screen appears...

**Comment by sejun2** [comment]
> Same here. on android, just a white screen appears...

I just removed new added logic from android side, then it works now.

**Comment by MalikSamiAwan** [comment]
same here
does anyone find any solution for that?

**Comment by prongbang** [comment]
Fixed 1.1.5

Thank you for report 👍
